# Generated by Django 5.0.7 on 2024-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_worker_groups_alter_worker_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
